accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'


urlpatterns = [
    path('dashboard' , views.dashboard , name='dashboard'),
    path('profile/' , views.profile , name='profile'),
    path('projects' , views.project_list , name='projects'),
    path('projects/<int:id>' , views.project_detail , name='project_detail'),

    path('employees/' , views.employee_management , name='employee_list'),
    path('employees/export/excel' , views.employee_export_excel , name='employee_export_excel'),
    path('employee/<int:id>' , views.employee_detail,name='employee_detail'),
    # path('employees/attendance' , views.employees_attendance , name='employees_attendance'),
    # path('employees/attendance/<int:id>' , views.employee_attendance , name='employee_attendance'),
    
]

employee/urls.py
from django.urls import path
from . import views

app_name = 'employee'


urlpatterns = [
    path('holidays' , views.holydays , name='holidays'),
    # vacation
    path('my-attendance' , views.my_attendance , name='my_attendance'),
    path('salary' , views.my_salary_list , name='my_salary_list'),
    path('loan' , views.my_loan , name='my_loan'),

    # overtime
    path('month-overtime' , views.month_overtime , name='month_overtime'),
    path('all-overtime' , views.all_overtime , name='overtime'),
    path('overtime/<int:id>' , views.delete_overtime , name='delete_overtime'),


    # reports
    # client
    path('training' , views.my_training , name='training'),
    path('promotions' , views.my_promotions , name='promotions'),
    path('resign' , views.add_resign , name='resign'),
    path('resign/<int:id>' , views.delete_resign , name='delete_resign'),
    path('assets' , views.my_assets , name='assets'),
     
]

hr/urls.py
from django.urls import path
from . import views

app_name = 'hr'


urlpatterns = [


    path('employee/add' , views.employee_create , name='employee_create'),
    path('employee/<int:id>/edit' , views.employee_edit , name='employee_edit'),
    path('employee/<int:id>/delete' , views.employee_delete , name='employee_delete'),
    path('employees/attendance' , views.employees_attendance , name='employees_attendance'),
    path('employees/attendance/<int:id>' , views.employee_attendance , name='employee_attendance'),
    path('employee/reports' , views.employee_info_report , name='employee_info_report'),


    path('departments/' , views.deparment_management , name='department_list'),
    path('departments/add' , views.department_create , name='department_create'),
    path('departments/add' , views.department_create , name='department_create'),
    path('departments/<int:id>/edit' , views.department_edit , name='department_edit'),
    path('departments/<int:id>/delete' , views.department_delete , name='department_delete'),


    path('jobs/' , views.job_management , name='job_list'),
    path('jobs/add' , views.job_create , name='job_create'),
    path('jobs/<int:id>/edit' , views.job_edit , name='job_edit'),
    path('jobs/<int:id>/delete' , views.job_delete , name='job_delete'),


    path('salary/' , views.employee_salary_management , name='employee_salary_management'),


    ## training
    path('training/' , views.training_management , name='training_list'),
    path('training/add' , views.training_create , name='training_create'),
    path('training/<int:id>/edit' , views.training_edit , name='training_edit'),
    path('training/<int:id>/delete' , views.training_delete , name='training_delete'),
    path('training/<int:id>/status_change' , views.training_staus_update , name='training_staus_update'),
    
    ## training type
    path('training-type/' , views.training_type_management , name='training_type_list'),
    path('training-type/create' , views.training_type_create , name='training_type_create'),
    path('training-type/<int:id>/edit' , views.training_type_edit , name='training_type_edit'),
    path('training-type/<int:id>/delete' , views.training_type_delete , name='training_type_delete'),
    path('training-type/<int:id>/status_change' , views.training_type_staus_update , name='training_type_staus_update'),
    

    ## promotions
    path('promotions/' , views.promotion_management , name='promotion_list'),
    path('promotions/add' , views.promotion_create, name='promotion_create'),
    path('promotions/<int:id>/edit' , views.promotion_edit , name='promotion_edit'),
    path('promotions/<int:id>/delete' , views.promotion_delete , name='promotion_delete'),


    ## payroll
    path('payroll/adition' , views.payroll_addition , name='payroll_addition'),
    path('payroll/adition/create' , views.payroll_addition_create , name='payroll_addition_create'),
    path('payroll/adition/<int:id>/edit' , views.payroll_addition_edit , name='payroll_addition_edit'),
    path('payroll/adition/<int:id>/delete' , views.payroll_addition_delte , name='payroll_addition_delte'),


    path('payroll/overtime' , views.payroll_overtime , name='payroll_overtime'),
    path('payroll/overtime/create' , views.payroll_overtime_create , name='payroll_overtime_create'),
    path('payroll/overtime/<int:id>/edit' , views.payroll_overtime_edit , name='payroll_overtime_edit'),
    path('payroll/overtime/<int:id>/delete' , views.payroll_overtime_delete , name='payroll_overtime_delete'),

    path('payroll/payslip' , views.payslip_view , name='payroll_payslip'),

    ## promotions
    path('assets/' , views.asset_management , name='asset_list'),
    path('assets/add' , views.asset_create , name='asset_create'),
    path('assets/<int:id>/edit' , views.asset_edit , name='asset_edit'),
    path('assets/<int:id>/delete' , views.asset_delete , name='asset_delete'),




    path('termination/' , views.employee_termination , name='employee_termination'),
    path('termination/add' , views.employee_termination , name='employee_termination'),
    path('termination/<int:id>/delete' , views.employee_termination_delete , name='employee_termination_delete'),
    
    path('holidays/' , views.employee_holidays , name='employee_holidays'),
    path('holidays/add' , views.holiday_create , name='holiday_create'),
    path('holidays/<int:id>/delete' , views.holiday_delete , name='holiday_delete'),


    path('announcements' , views.all_anouncements , name='all_anouncements'),


    path('settings/company' , views.company_settings , name='company_settings')

]

project/urls.py
from django.urls import path , include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from settings.views import handel500

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('' , include('website.urls',namespace='website')),
    path('' , include('accounts.urls',namespace='accounts')),
    path('' , include('hr.urls',namespace='hr')),
    path('' , include('employee.urls',namespace='employee')),
    path('' , include('managers.urls',namespace='manager')),
    path('settings/' , include('settings.urls',namespace='setings')),
    path('500' , handel500, name='500_error'),

]



handler404= "settings.views.handel404"
handler500= "settings.views.handel500"


if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/views.py
from django.shortcuts import render
from managers.models import Project , Client
from managers.forms import ProjectForm
from django.contrib import messages
from django.shortcuts  import get_object_or_404
from .models import User , UserAttendance , UserProfile , UserJob , UserContact , UserSalary , UserSocialInsurance , UserMedicalInsurance , UserFollowers
import datetime
import settings.models as st_models
from .forms import UserForm , UserProfileForm
from django.http import HttpResponse
import xlwt
from django.contrib.auth.decorators import login_required
from django.db.models import Count

@login_required
def dashboard(request):
    if request.user.is_hr:
        projects_count = Project.objects.all().count()
        clients_count = Client.objects.all().count()
        employee_count= User.objects.all().count()
        pending_requests_count = ''


        # context['categories'] = Category.objects.all().annotate(post_count=Count('post_category'))

        # section = st_models.Department_Section.objects.all().annotate(employee_count=Count('user_department_section'))

        # section_data = [{'y':i.name,'a':i.employee_count} for i in section]

        # print(section_data)


        dataset = st_models.Department_Section.objects.values('name').annotate(employee_count=Count('user_department_section'))

        print(dataset)

        context = {
            'projects_count' : projects_count , 
            'clients_count' : clients_count , 
            'employee_count' : employee_count , 
            'pending_requests_count' : pending_requests_count , 
            'data' : dataset

        }

        return render(request,'hr/dashboard.html',context)


    elif request.user.is_manager:
        return render(request,'managers/dashboard.html',{})

    
    else:
        return render(request,'employee/dashboard.html',{})




#### user
def profile(request):
    user_profile = get_object_or_404(UserProfile , user=request.user)
    # user_contact = get_object_or_404(UserContact , user=request.user)
    # user_job = get_object_or_404(UserJob, user=request.user)
    # user_salary = get_object_or_404(UserSalary, user=request.user)
    # social_insurance = get_object_or_404(UserSocialInsurance , user=request.user)
    # media_insuarance = get_object_or_404(UserMedicalInsurance , user=request.user)
    # user_followers = UserFollowers.objects.filter(user=request.user)

    return render(request,'accounts/profile.html',{
        'user_profile' : user_profile , 
        # 'user_contact' : user_contact , 
        # 'user_job' : user_job , 
        # 'user_salary' : user_salary , 
        # 'social_insurance' : social_insurance , 
        # 'media_insuarance' : media_insuarance , 
        # 'user_followers' : user_followers
    })




@login_required
def project_list(request):
    projects = Project.objects.filter(manager=request.user)
    return render(request,'accounts/projects.html',{'object_list':projects})


@login_required
def project_detail(request,id):
    project = get_object_or_404(Project , id=id)
    return render(request,'accounts/project-view.html',{'project':project})


@login_required
def employee_management(request):
    if request.user.is_hr:
        employees = User.objects.all()

    elif request.user.is_manager:
        employees = User.objects.all()  ## filter by current manager
 
    return render(request,'accounts/employees.html',{'object_list':employees})



@login_required
def employee_detail(request,id):
    user_profile = get_object_or_404(UserProfile , user=request.user)
    return render(request,'accounts/profile.html',{'user_profile':user_profile})


@login_required
def employee_export_excel(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['content-Disposition'] = 'attachement; filename=employees' + str(datetime.datetime.now())+'.xls'
    wb = xlwt.Workbook(encoding='utf-8')
    sheet1 = wb.add_sheet('Employees')
    font_style = xlwt.XFStyle()
    font_style.font.blod=True  

    # row_num = 0
    # columns = ['ar_name' , 'en_name']

    # for col_num in range(len(columns)):
    #     ws.write(row_num , col_num , columns[col_num] , font_style)

    # employees = User.objects.all()
    # for row in employees:
    #     row_num += 1

    #     print(row)

    #     for col_num in range(len(row)):
    #         ws.write(row_num,col_num,str(row[col_num]),font_style)


    sheet1.write(0,1, "ar name")
    sheet1.write(0,2,"en name")


    ''' export : 
        - name  -job title  -hire date  -job_id  -department  -manager'''

    row_number = 2
    employees = UserProfile.objects.all().values_list('ar_name','en_name','job_number')
    for row in employees :
        column_num = 1
        for item in row :
            sheet1.write(row_number,column_num,str(item) )
            column_num = column_num + 1
        row_number = row_number + 1

    wb.save(response)
    return response

employee/views.py
from django.shortcuts import render , redirect
from accounts import models , forms
from settings import models as st_models
import datetime
from django.db.models import Sum
from collections import Counter
from django.shortcuts  import get_object_or_404
from django.contrib import messages
import managers.models as mn_models
from django.contrib.auth.decorators import login_required
# Create your views here.

def holydays(request):
    today = datetime.datetime.now()
    holidays = st_models.Holiday.objects.filter(date_from__year=today.year)
    return render(request,'employee/holidays.html',{'holidays':holidays , 'today_year' : today.year})


def add_vacation(request):
    messages.success(request, 'Successfully Added a New Vacation')



def my_attendance(request):
    
    return render(request,'employee/attendance-employee.html',{})



def month_overtime(request):
    today = datetime.date.today()
    overtime = models.UserOverTime.objects.filter(user=request.user , date__month=today.month)
    # accepted_overtime = models.UserOverTime.objects.filter(user=request.user , status='Approved' , date__month=today.month).aggregate(Sum('overhours'))
    # rejected_overtime = models.UserOverTime.objects.filter(user=request.user , status='Rejected'  , date__month=today.month).aggregate(Sum('overhours'))
    # pending_overtime = models.UserOverTime.objects.filter(user=request.user , status='Pending', date__month=today.month).aggregate(Sum('overhours'))
    # total = Counter(accepted_overtime)  + Counter(rejected_overtime) + Counter(pending_overtime)
    
    accepted_overtime = models.UserOverTime.objects.filter(user=request.user , status='Approved', date__month=today.month).count()
    rejected_overtime = models.UserOverTime.objects.filter(user=request.user , status='Rejected', date__month=today.month).count()
    pending_overtime = models.UserOverTime.objects.filter(user=request.user , status='Pending', date__month=today.month).count()
    total = models.UserOverTime.objects.filter(user=request.user , status='Approved' , date__month=today.month).aggregate(Sum('overhours'))

    if request.method == 'POST':
        form = forms.OvertimeForm(request.POST)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.user = request.user
            myform.save()
            messages.success(request, 'Successfully Added a New overtime')

    else:
        form = forms.OvertimeForm()
    return render(request,'employee/overtime.html',{
        'overtime' : overtime ,
        'form': form ,
        'accepted_overtime': accepted_overtime , 
        'rejected_overtime' : rejected_overtime , 
        'pending_overtime' : pending_overtime,
        'total' : total
        })


def all_overtime(request):
    today = datetime.date.today()
    overtime = models.UserOverTime.objects.filter(user=request.user)
    accepted_overtime = models.UserOverTime.objects.filter(user=request.user , status='Approved').count()
    rejected_overtime = models.UserOverTime.objects.filter(user=request.user , status='Rejected').count()
    pending_overtime = models.UserOverTime.objects.filter(user=request.user , status='Pending').count()
    total = models.UserOverTime.objects.filter(user=request.user , status='Approved' ).aggregate(Sum('overhours'))

    return render(request,'employee/all-overtime.html',{
        'overtime' : overtime ,
        'accepted_overtime': accepted_overtime , 
        'rejected_overtime' : rejected_overtime , 
        'pending_overtime' : pending_overtime,
        'total' : total
        })



def edit_overtime(request):
    pass


def delete_overtime(request,id):
    overtime = get_object_or_404(models.UserOverTime , id=id)
    overtime.delete()
    messages.warning(request, 'Successfully Deleted ')
    return redirect('/employee/month-overtime')




def my_salary_list(request):
    
    return render(request,'employee/salary-view.html',{})



def project_report_list(request):
    pass

def project_report_detail(request):
    pass



def cliet_info(request):
    pass


def my_performance_review(request):
    pass



def my_performance_review_approve(request):
    pass



def my_performance_appraisel_review(request):
    pass



def my_performance_review_appraisel_approve(request):
    pass



def my_training(request):
    my_training = models.UserTraining.objects.filter(employees__id=request.user.id)
    return render(request,'employee/training.html',{'my_training': my_training})


def my_promotions(request):
    my_promotions = models.UserPromotion.objects.filter(user=request.user)
    return render(request,'employee/promotion.html',{'my_promotions':my_promotions})


def add_resign(request):
    my_resigns = models.UserResign.objects.filter(user=request.user)
    if request.method == 'POST':
        form = forms.UserResignForm(request.POST)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.user = request.user
            myform.save()

    else:
        form = forms.UserResignForm()
    return render(request,'employee/resignation.html',{'my_resigns':my_resigns,'form':form})


def delete_resign(request,id):
    resign = get_object_or_404(models.UserResign , id=id)
    resign.delete()
    messages.warning(request, 'Successfully Deleted ')
    return redirect('/resign')




def my_assets(request):
    my_assets = models.UserAssets.objects.filter(user=request.user)
    return render(request,'employee/assets.html',{'my_assets':my_assets})


def my_loan(request):

    return render(request,'employee/loan.html',{})

accounts/templates/includes/employee/employee_create.html
{% load i18n %}
{% load bootstrap4 %}
<div class="modal-header">
    <h5 class="modal-title">{% trans 'Add Employee' %}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form method="POST" class="form employee_create_from" action="{% url 'hr:employee_create' %}">
        {% csrf_token %}


        {% bootstrap_form userform %}
        {% bootstrap_form userprofileform %}

        <div class="row">
            {% buttons %}
            <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
            {% endbuttons %}
        
            </div>

    </form>
</div>

accounts/templates/includes/employee/employee_delete.html
{% load i18n %}
<div class="modal-body">
    <div class="form-header">
        <h3>{% trans 'Delete Employee' %}</h3>
        <p>{% trans 'Are you sure want to delete?' %}</p>
    </div>
    <div class="modal-btn delete-action">
        <form method="POST" class="employee_delete_from" action="{% url 'hr:employee_delete' employee.id %}">
            {% csrf_token %}
            <div class="row">
                <div class="col-6">
                    <button type="submit" class="btn btn-primary continue-btn">{% trans 'Delete' %}</button>
                </div>
                <div class="col-6">
                    <a href="javascript:void(0);" data-dismiss="modal" class="btn btn-primary cancel-btn">{% trans 'Cancel' %}</a>
                </div>
            </div>
        </form>
    </div>
</div>

accounts/templates/includes/employee/employee_list.html
{% load i18n %}
{% for employee in object_list %}
<div class="col-md-4 col-sm-6 col-12 col-lg-4 col-xl-3">
    <div class="profile-widget">
        <div class="profile-img">
            <a href="{% url 'accounts:employee_detail' employee.id %}" class="avatar">
                
                {% if employee.user_profile.image %}
                    <img src="{{employee.user_profile.image.url}}" alt="">
                {% endif %}
                    
                
            </a>
        </div>
        
        {% if request.user.is_hr %}
            <div class="dropdown profile-action">
                <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i
                        class="material-icons">more_vert</i></a>
                <div class="dropdown-menu dropdown-menu-right">
                    <button class="dropdown-item btn btn-info btn-sm-x  js-update" data-url="{% url 'hr:employee_edit' employee.id %}"><i class="fa fa-pencil m-r-5"></i> {% trans 'Edit' %} </button>
                    <button class="dropdown-item btn btn-danger btn-sm-x js-delete" data-url="{% url 'hr:employee_delete' employee.id %}"><i class="fa fa-trash-o m-r-5"></i> {% trans 'Delete' %} </button>
                
                </div>
            </div>
        {% endif %}
            

        <h4 class="user-name m-t-10 mb-0 text-ellipsis"><a
                href="{% url 'accounts:employee_detail' employee.id %}">{{employee.user_profile.en_name}}</a></h4>
        <div class="small text-muted">{{employee.user_job.job_type}}</div>
    </div>
</div>
{% endfor %}

accounts/templates/includes/employee/employee_update.html
{% load i18n %}
{% load bootstrap4 %}
<div class="modal-header">
    <h5 class="modal-title">{% trans 'Edit Employee' %}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form method="POST" enctype="multipart/form-data" class="form employee_save_from" action="{% url 'hr:employee_edit' userform.instance.pk %}">
        {% csrf_token %}

        <div class="row">
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userform.username  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.ar_name  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.en_name  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.job_number  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.social_status  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.id_number  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.id_create_date  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.id_end_date  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.id_issue_location  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.gender  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.visa_number  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.birth_date  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.birth_location  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.passport_number  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.passport_issue_date  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.passport_end_date  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.borders_number  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.job  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.religion  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.nationality  %}
            </div>
            <div class="col-lg-6 col-md-12">
                {% bootstrap_field userprofileform.id_card_date  %}
            </div>




        </div>
        <div class="row">
            {% buttons %}
            <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
            {% endbuttons %}
        
            </div>

    </form>
</div>