employee/urls.py
from django.urls import path
from . import views

app_name = 'employee'


urlpatterns = [
    path('holidays' , views.holydays , name='holidays'),
    # vacation
    path('my-attendance' , views.my_attendance , name='my_attendance'),
    path('salary' , views.my_salary_list , name='my_salary_list'),
    path('loan' , views.my_loan , name='my_loan'),

    # overtime
    path('month-overtime' , views.month_overtime , name='month_overtime'),
    path('all-overtime' , views.all_overtime , name='overtime'),
    path('overtime/<int:id>' , views.delete_overtime , name='delete_overtime'),


    # reports
    # client
    path('training' , views.my_training , name='training'),
    path('promotions' , views.my_promotions , name='promotions'),
    path('resign' , views.add_resign , name='resign'),
    path('resign/<int:id>' , views.delete_resign , name='delete_resign'),
    path('assets' , views.my_assets , name='assets'),
     
]

hr/urls.py
from django.urls import path
from . import views

app_name = 'hr'


urlpatterns = [


    path('employee/add' , views.employee_create , name='employee_create'),
    path('employee/<int:id>/edit' , views.employee_edit , name='employee_edit'),
    path('employee/<int:id>/delete' , views.employee_delete , name='employee_delete'),
    path('employees/attendance' , views.employees_attendance , name='employees_attendance'),
    path('employees/attendance/<int:id>' , views.employee_attendance , name='employee_attendance'),
    path('employee/reports' , views.employee_info_report , name='employee_info_report'),


    path('departments/' , views.deparment_management , name='department_list'),
    path('departments/add' , views.department_create , name='department_create'),
    path('departments/add' , views.department_create , name='department_create'),
    path('departments/<int:id>/edit' , views.department_edit , name='department_edit'),
    path('departments/<int:id>/delete' , views.department_delete , name='department_delete'),


    path('jobs/' , views.job_management , name='job_list'),
    path('jobs/add' , views.job_create , name='job_create'),
    path('jobs/<int:id>/edit' , views.job_edit , name='job_edit'),
    path('jobs/<int:id>/delete' , views.job_delete , name='job_delete'),


    path('salary/' , views.employee_salary_management , name='employee_salary_management'),


    ## training
    path('training/' , views.training_management , name='training_list'),
    path('training/add' , views.training_create , name='training_create'),
    path('training/<int:id>/edit' , views.training_edit , name='training_edit'),
    path('training/<int:id>/delete' , views.training_delete , name='training_delete'),
    path('training/<int:id>/status_change' , views.training_staus_update , name='training_staus_update'),
    
    ## training type
    path('training-type/' , views.training_type_management , name='training_type_list'),
    path('training-type/create' , views.training_type_create , name='training_type_create'),
    path('training-type/<int:id>/edit' , views.training_type_edit , name='training_type_edit'),
    path('training-type/<int:id>/delete' , views.training_type_delete , name='training_type_delete'),
    path('training-type/<int:id>/status_change' , views.training_type_staus_update , name='training_type_staus_update'),
    

    ## promotions
    path('promotions/' , views.promotion_management , name='promotion_list'),
    path('promotions/add' , views.promotion_create, name='promotion_create'),
    path('promotions/<int:id>/edit' , views.promotion_edit , name='promotion_edit'),
    path('promotions/<int:id>/delete' , views.promotion_delete , name='promotion_delete'),


    ## payroll
    path('payroll/adition' , views.payroll_addition , name='payroll_addition'),
    path('payroll/adition/create' , views.payroll_addition_create , name='payroll_addition_create'),
    path('payroll/adition/<int:id>/edit' , views.payroll_addition_edit , name='payroll_addition_edit'),
    path('payroll/adition/<int:id>/delete' , views.payroll_addition_delte , name='payroll_addition_delte'),


    path('payroll/overtime' , views.payroll_overtime , name='payroll_overtime'),
    path('payroll/overtime/create' , views.payroll_overtime_create , name='payroll_overtime_create'),
    path('payroll/overtime/<int:id>/edit' , views.payroll_overtime_edit , name='payroll_overtime_edit'),
    path('payroll/overtime/<int:id>/delete' , views.payroll_overtime_delete , name='payroll_overtime_delete'),

    path('payroll/payslip' , views.payslip_view , name='payroll_payslip'),

    ## promotions
    path('assets/' , views.asset_management , name='asset_list'),
    path('assets/add' , views.asset_create , name='asset_create'),
    path('assets/<int:id>/edit' , views.asset_edit , name='asset_edit'),
    path('assets/<int:id>/delete' , views.asset_delete , name='asset_delete'),




    path('termination/' , views.employee_termination , name='employee_termination'),
    path('termination/add' , views.employee_termination , name='employee_termination'),
    path('termination/<int:id>/delete' , views.employee_termination_delete , name='employee_termination_delete'),
    
    path('holidays/' , views.employee_holidays , name='employee_holidays'),
    path('holidays/add' , views.holiday_create , name='holiday_create'),
    path('holidays/<int:id>/delete' , views.holiday_delete , name='holiday_delete'),


    path('announcements' , views.all_anouncements , name='all_anouncements'),


    path('settings/company' , views.company_settings , name='company_settings')

]

project/urls.py
from django.urls import path , include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from settings.views import handel500

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('' , include('website.urls',namespace='website')),
    path('' , include('accounts.urls',namespace='accounts')),
    path('' , include('hr.urls',namespace='hr')),
    path('' , include('employee.urls',namespace='employee')),
    path('' , include('managers.urls',namespace='manager')),
    path('settings/' , include('settings.urls',namespace='setings')),
    path('500' , handel500, name='500_error'),

]



handler404= "settings.views.handel404"
handler500= "settings.views.handel500"


if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/models.py
from django.db import models

# Create your models here.

hr/models.py
from django.db import models
# Create your models here.
from django.utils import timezone
from django.conf import settings
from django.utils.translation import gettext_lazy as _
import settings.models as st_model


class Announcement(models.Model):
    company  = models.ForeignKey(st_model.Company, related_name='company_announcement', on_delete=models.CASCADE)
    title = models.CharField(_("Title"),max_length=200)
    message = models.TextField(_("Message"),max_length=1000)
    created_at = models.DateTimeField(_("Created At"),default=timezone.now) 
    watched = models.ManyToManyField(settings.AUTH_USER_MODEL ,verbose_name=_("Watched Users"), blank=True, null=True)


    def __str__(self):
        return self.title

employee/views.py
from django.shortcuts import render , redirect
from accounts import models , forms
from settings import models as st_models
import datetime
from django.db.models import Sum
from collections import Counter
from django.shortcuts  import get_object_or_404
from django.contrib import messages
import managers.models as mn_models
from django.contrib.auth.decorators import login_required
# Create your views here.

def holydays(request):
    today = datetime.datetime.now()
    holidays = st_models.Holiday.objects.filter(date_from__year=today.year)
    return render(request,'employee/holidays.html',{'holidays':holidays , 'today_year' : today.year})


def add_vacation(request):
    messages.success(request, 'Successfully Added a New Vacation')



def my_attendance(request):
    
    return render(request,'employee/attendance-employee.html',{})



def month_overtime(request):
    today = datetime.date.today()
    overtime = models.UserOverTime.objects.filter(user=request.user , date__month=today.month)
    # accepted_overtime = models.UserOverTime.objects.filter(user=request.user , status='Approved' , date__month=today.month).aggregate(Sum('overhours'))
    # rejected_overtime = models.UserOverTime.objects.filter(user=request.user , status='Rejected'  , date__month=today.month).aggregate(Sum('overhours'))
    # pending_overtime = models.UserOverTime.objects.filter(user=request.user , status='Pending', date__month=today.month).aggregate(Sum('overhours'))
    # total = Counter(accepted_overtime)  + Counter(rejected_overtime) + Counter(pending_overtime)
    
    accepted_overtime = models.UserOverTime.objects.filter(user=request.user , status='Approved', date__month=today.month).count()
    rejected_overtime = models.UserOverTime.objects.filter(user=request.user , status='Rejected', date__month=today.month).count()
    pending_overtime = models.UserOverTime.objects.filter(user=request.user , status='Pending', date__month=today.month).count()
    total = models.UserOverTime.objects.filter(user=request.user , status='Approved' , date__month=today.month).aggregate(Sum('overhours'))

    if request.method == 'POST':
        form = forms.OvertimeForm(request.POST)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.user = request.user
            myform.save()
            messages.success(request, 'Successfully Added a New overtime')

    else:
        form = forms.OvertimeForm()
    return render(request,'employee/overtime.html',{
        'overtime' : overtime ,
        'form': form ,
        'accepted_overtime': accepted_overtime , 
        'rejected_overtime' : rejected_overtime , 
        'pending_overtime' : pending_overtime,
        'total' : total
        })


def all_overtime(request):
    today = datetime.date.today()
    overtime = models.UserOverTime.objects.filter(user=request.user)
    accepted_overtime = models.UserOverTime.objects.filter(user=request.user , status='Approved').count()
    rejected_overtime = models.UserOverTime.objects.filter(user=request.user , status='Rejected').count()
    pending_overtime = models.UserOverTime.objects.filter(user=request.user , status='Pending').count()
    total = models.UserOverTime.objects.filter(user=request.user , status='Approved' ).aggregate(Sum('overhours'))

    return render(request,'employee/all-overtime.html',{
        'overtime' : overtime ,
        'accepted_overtime': accepted_overtime , 
        'rejected_overtime' : rejected_overtime , 
        'pending_overtime' : pending_overtime,
        'total' : total
        })



def edit_overtime(request):
    pass


def delete_overtime(request,id):
    overtime = get_object_or_404(models.UserOverTime , id=id)
    overtime.delete()
    messages.warning(request, 'Successfully Deleted ')
    return redirect('/employee/month-overtime')




def my_salary_list(request):
    
    return render(request,'employee/salary-view.html',{})



def project_report_list(request):
    pass

def project_report_detail(request):
    pass



def cliet_info(request):
    pass


def my_performance_review(request):
    pass



def my_performance_review_approve(request):
    pass



def my_performance_appraisel_review(request):
    pass



def my_performance_review_appraisel_approve(request):
    pass



def my_training(request):
    my_training = models.UserTraining.objects.filter(employees__id=request.user.id)
    return render(request,'employee/training.html',{'my_training': my_training})


def my_promotions(request):
    my_promotions = models.UserPromotion.objects.filter(user=request.user)
    return render(request,'employee/promotion.html',{'my_promotions':my_promotions})


def add_resign(request):
    my_resigns = models.UserResign.objects.filter(user=request.user)
    if request.method == 'POST':
        form = forms.UserResignForm(request.POST)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.user = request.user
            myform.save()

    else:
        form = forms.UserResignForm()
    return render(request,'employee/resignation.html',{'my_resigns':my_resigns,'form':form})


def delete_resign(request,id):
    resign = get_object_or_404(models.UserResign , id=id)
    resign.delete()
    messages.warning(request, 'Successfully Deleted ')
    return redirect('/resign')




def my_assets(request):
    my_assets = models.UserAssets.objects.filter(user=request.user)
    return render(request,'employee/assets.html',{'my_assets':my_assets})


def my_loan(request):

    return render(request,'employee/loan.html',{})

hr/templates/hr/assets.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load bootstrap4 %}
{% block body %}

			<!-- Page Wrapper -->
            <div class="page-wrapper">
			
				<!-- Page Content -->
                <div class="content container-fluid">
				
					<!-- Page Header -->
					<div class="page-header">
						<div class="row align-items-center">
							<div class="col">
								<h3 class="page-title">{% trans 'Assets' %}</h3>
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><a href="">{% trans 'Dashboard' %}</a></li>
									<li class="breadcrumb-item active">{% trans 'Assets' %}</li>
								</ul>
							</div>
							<div class="col-auto float-right ml-auto">
								<button class="btn add-btn js-create" data-url="{% url 'hr:asset_create' %}"><i class="fa fa-plus"></i>{% trans 'Add New' %} </button>
							</div>
						</div>
					</div>
					<!-- /Page Header -->
					
					<!-- Search Filter -->
					<div class="row filter-row">
						<div class="col-sm-6 col-md-3">  
							<div class="form-group form-focus">
								<input type="text" class="form-control floating">
								<label class="focus-label">{% trans 'Employee Name' %}</label>
							</div>
						</div>
						<div class="col-sm-6 col-md-3"> 
							<div class="form-group form-focus select-focus">
								<select class="select floating"> 
									<option value=""> -- Select -- </option>
									<option value="0"> Pending </option>
									<option value="1"> Approved </option>
									<option value="2"> Returned </option>
								</select>
								<label class="focus-label">Status</label>
							</div>
						</div>
						<div class="col-sm-12 col-md-4">  
						   <div class="row">  
							   <div class="col-md-6 col-sm-6">  
									<div class="form-group form-focus">
										<div class="cal-icon">
											<input class="form-control floating datetimepicker" type="text">
										</div>
										<label class="focus-label">From</label>
									</div>
								</div>
							   <div class="col-md-6 col-sm-6">  
									<div class="form-group form-focus">
										<div class="cal-icon">
											<input class="form-control floating datetimepicker" type="text">
										</div>
										<label class="focus-label">To</label>
									</div>
								</div>
							</div>
						</div>
						<div class="col-sm-6 col-md-2">  
							<a href="#" class="btn btn-success btn-block"> Search </a>  
						</div>     
                    </div>
					<!-- /Search Filter -->
					
					<div class="row">
						<div class="col-md-12">
							<div class="table-responsive">
								<table class="table table-striped custom-table mb-0 datatable" id="asset-table">
									<thead>
										<tr>
											<th>{% trans 'Asset User' %}</th>
											<th>{% trans 'Asset Name' %}</th>
											<th>{% trans 'Asset Id' %}</th>
											<th>{% trans 'Purchase Date' %}</th>
											<th>{% trans 'Warrenty' %}</th>
											<th>{% trans 'Warrenty End' %}</th>
											<th>{% trans 'Amount' %}</th>
											<th class="text-center">{% trans 'Status' %}</th>
											<th class="text-right"></th>
										</tr>
									</thead>
									<tbody>										
										{% include 'includes/asset_list.html' %}
									</tbody>
								</table>
							</div>
						</div>
					</div>
                </div>
				<!-- /Page Content -->
			
				<!-- Add Asset Modal -->
				<div id="add_asset" class="modal custom-modal fade" role="dialog">
					<div class="modal-dialog modal-md" role="document">
						<div class="modal-content">

						</div>
					</div>
				</div>
				<!-- /Add Asset Modal -->

            </div>
			<!-- /Page Wrapper -->
			{% endblock body %}


			{% block javascript %}
			<script src="{% static 'hr/handel_asset_ajax.js' %}"></script>		  
			{% endblock javascript %}

hr/templates/hr/departments.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load bootstrap4 %}
{% block body %}
<!-- Page Wrapper -->
<div class="page-wrapper">

	<!-- Page Content -->
	<div class="content container-fluid">

		<!-- Page Header -->
		<div class="page-header">
			<div class="row align-items-center">
				<div class="col">
					<h3 class="page-title">{% trans 'Department' %}</h3>
					<ul class="breadcrumb">
						<li class="breadcrumb-item"><a href="">{% trans 'Dashboard' %}</a></li>
						<li class="breadcrumb-item active">{% trans 'Department' %}</li>
					</ul>
				</div>
				<div class="col-auto float-right ml-auto">
					<button class="btn add-btn js-create" data-url="{% url 'hr:department_create' %}"><i class="fa fa-plus"></i> {% trans 'Add Department' %}</button>
				</div>
			</div>
		</div>
		<!-- /Page Header -->

		<div class="row">
			<div class="col-md-12">
				<div>
					<table class="table table-striped custom-table mb-0 datatable" id="departments-table">
						<thead>
							<tr>
								<th style="width: 30px;">#</th>
								<th>{% trans 'Department Name' %}</th>
								<th class="text-right">{% trans 'Action' %}</th>
							</tr>
						</thead>
						<tbody>

							{% include "includes/departments_list.html" %}

						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="row" style="margin-top: 10px;">
			<div class="col-sm-12 col-md-5">
				<div class="dataTables_info" id="DataTables_Table_0_info" role="status" aria-live="polite">
					{% trans 'Showing' %} {{departments|length}} of {{depratments_count}} {% trans 'entries' %} </div>
			</div>
			<div class="col-sm-12 col-md-7">
				<div class="dataTables_paginate paging_simple_numbers" id="DataTables_Table_0_paginate">
					{% if departments.has_other_pages %}
						<ul class="pagination">
							{% if departments.has_previous %}
								<li class="paginate_button page-item previous " id="DataTables_Table_0_previous"><a
									href="?page={{ departments.previous_page_number }}" aria-controls="DataTables_Table_0" data-dt-idx="0" tabindex="0"
									class="page-link">{% trans 'Previous' %}</a></li>
							{% else %}
								<li class="paginate_button page-item previous disabled" id="DataTables_Table_0_previous"><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="0" tabindex="0"
									class="page-link">{% trans 'Previous' %}</a></li>
							{% endif%}

							{% for i in departments.paginator.page_range %}
								{% if departments.number == i %}
									<li class="paginate_button page-item active"><a href="#" aria-controls="DataTables_Table_0"
										data-dt-idx="1" tabindex="0" class="page-link">{{ i }} </a></li>
								{% else %}
									<li class="paginate_button page-item active"><a href="?page={{ i }}" aria-controls="DataTables_Table_0"
										data-dt-idx="1" tabindex="0" class="page-link">{{ i }}</a></li>
								{% endif %}
							{% endfor %}

							{% if departments.has_next %}		
								<li class="paginate_button page-item next " id="DataTables_Table_0_next"><a href="?page={{ departments.next_page_number }}"
									aria-controls="DataTables_Table_0" data-dt-idx="2" tabindex="0"
									class="page-link">{% trans 'Next' %}</a></li>
							{% else %}
								<li class="paginate_button page-item next disabled" id="DataTables_Table_0_next"><a href="#"
									aria-controls="DataTables_Table_0" data-dt-idx="2" tabindex="0"
									class="page-link">{% trans 'Next' %}</a></li>
							{% endif %}
						</ul>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
	<!-- /Page Content -->



	<!-- Edit Department Modal -->
	<div id="edit_department" class="modal custom-modal fade" role="dialog">
		<div class="modal-dialog modal-dialog-centered" role="document">
			<div class="modal-content">

			</div>
		</div>
	</div>
	<!-- /Edit Department Modal -->


</div>
<!-- /Page Wrapper -->
{% endblock body %}

{% block javascript %}
<script src="{% static 'hr/handel_departments_ajax.js' %}"></script>		  
{% endblock javascript %}

hr/templates/hr/payroll-addition.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap4 %}
{% block body %}
			<!-- Page Wrapper -->
            <div class="page-wrapper">
			
				<!-- Page Content -->
                <div class="content container-fluid">
				
					<!-- Page Header -->
					<div class="page-header">
						<div class="row align-items-center">
							<div class="col">
								<h3 class="page-title">{% trans 'Payroll' %}</h3>
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><a href="">{% trans 'Dashboard' %}</a></li>
									<li class="breadcrumb-item active">{% trans 'Payroll' %}</li>
									<li class="breadcrumb-item active">{% trans 'Addition & Duduction' %}</li>
								</ul>
							</div>
							<div class="col-auto float-right ml-auto">
								<button class="btn add-btn js-create" data-url="{% url 'hr:payroll_addition_create' %}"><i class="fa fa-plus"></i> {% trans 'Add' %}</button>
							</div>
						</div>
					</div>
					<!-- /Page Header -->
					
					<div class="row">
						<div class="col-md-12">
							<div class="table-responsive">
								<table class="table table-striped custom-table mb-0 datatable" id="addition-table">
									<thead>
										<tr>
											<th style="width: 30px;">#</th>
											<th>{% trans 'User' %} </th>
											<th>{% trans 'Replacement Type' %} </th>
											<th>{% trans 'Percentage ' %} </th>
											<th>{% trans 'Money ' %} </th>
											<th>{% trans 'Category ' %} </th>
											<th>{% trans 'Replacement For ' %} </th>
											<th>{% trans 'Notes ' %} </th>
											<th class="text-right">{% trans 'Action' %}</th>
										</tr>
									</thead>
									<tbody>
										{% include 'includes/payroll_addition_list.html' %}
									</tbody>
								</table>
							</div>
						</div>
					</div>
                </div>
				<!-- /Page Content -->

				<!-- Edit Designation Modal -->
				<div id="edit_designation" class="modal custom-modal fade" role="dialog">
					<div class="modal-dialog modal-dialog-centered" role="document">
						<div class="modal-content">

						</div>
					</div>
				</div>
				<!-- /Edit Designation Modal -->
				

			
            </div>
	
{% endblock body %}
{% block javascript %}
<script src="{% static 'hr/handel_payroll_addition.js' %}"></script>		  
{% endblock javascript %}

hr/templates/hr/termination.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
			<!-- Page Wrapper -->
            <div class="page-wrapper">
			
				<!-- Page Content -->
                <div class="content container-fluid">
				
					<!-- Page Header -->
					<div class="page-header">
						<div class="row align-items-center">
							<div class="col">
								<h3 class="page-title">Termination</h3>
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
									<li class="breadcrumb-item active">Termination</li>
								</ul>
							</div>
							<div class="col-auto float-right ml-auto">
								<a href="#" class="btn add-btn" data-toggle="modal" data-target="#add_termination"><i class="fa fa-plus"></i> Add Termination</a>
							</div>
						</div>
					</div>
					<!-- /Page Header -->
					
					<div class="row">
						<div class="col-md-12">
							<div class="table-responsive">
								<table class="table table-striped custom-table mb-0 datatable">
									<thead>
										<tr>
											<th>#</th>
											<th>Terminated Employee </th>
											<th>Department</th>
											<th>Termination Type </th>
											<th>Termination Date </th>
											<th>Reason</th>
											<th>Notice Date </th>
											<th class="text-right">Action</th>
										</tr>
									</thead>
									<tbody>
										
										{% for object in terminations %}	
											<tr>
												<td>{{forloop.counter}}</td>
												<td>
													<h2 class="table-avatar blue-link">
														<a href="profile.html" class="avatar"><img alt="" src="{{object.user.user_profile.image.url}}"></a>
														<a href="profile.html">{{object.user.username}}</a>
													</h2>
												</td>
												<td>{{object.user.user_job.department_section}}</td>
												<td>{{object.termination_type}}</td>
												<td>{{object.termination_date}}</td>
												<td>{{object.reason}}</td>
												<td>{{object.notice_date}}</td>
												<td class="text-right">
													<div class="dropdown dropdown-action">
														<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="material-icons">more_vert</i></a>
														<div class="dropdown-menu dropdown-menu-right">
															<a class="dropdown-item" href="#" data-toggle="modal" data-target="#edit_termination"><i class="fa fa-pencil m-r-5"></i> Edit</a>
															<a class="dropdown-item" href="#" data-toggle="modal" data-target="#delete_termination{{object.id}}"><i class="fa fa-trash-o m-r-5"></i> Delete</a>
														</div>
													</div>
												</td>
											</tr>
										<!-- Delete Termination Modal -->
										<div class="modal custom-modal fade" id="delete_termination{{object.id}}" role="dialog">
											<div class="modal-dialog modal-dialog-centered">
												<div class="modal-content">
													<div class="modal-body">
														<div class="form-header">
															<h3>Delete Termination</h3>
															<p>Are you sure want to delete?</p>
														</div>
														<div class="modal-btn delete-action">
															<div class="row">
																<div class="col-6">
																	<a href="{% url 'hr:employee_termination_delete' object.id %}" class="btn btn-primary continue-btn">Delete</a>
																</div>
																<div class="col-6">
																	<a href="javascript:void(0);" data-dismiss="modal" class="btn btn-primary cancel-btn">Cancel</a>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
										<!-- /Delete Termination Modal -->
										{% endfor %}
									</tbody>
								</table>
							</div>
						</div>
					</div>
                </div>
				<!-- /Page Content -->

				<!-- Add Termination Modal -->
				<div id="add_termination" class="modal custom-modal fade" role="dialog">
					<div class="modal-dialog modal-dialog-centered" role="document">
						<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title">Add Termination</h5>
								<button type="button" class="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
							<div class="modal-body">
								<form method="POST">
									{% csrf_token %}
									{% bootstrap_form form %}
									{% buttons %}
									<button type="submit" class="btn btn-primary">Submit</button>
									{% endbuttons %}
								</form>
							</div>
						</div>
					</div>
				</div>
				<!-- /Add Termination Modal -->
				
				<!-- Edit Termination Modal -->
				<div id="edit_termination" class="modal custom-modal fade" role="dialog">
					<div class="modal-dialog modal-dialog-centered" role="document">
						<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title">Edit Termination</h5>
								<button type="button" class="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
							<div class="modal-body">
								<form>
									<div class="form-group">
										<label>Terminated Employee <span class="text-danger">*</span></label>
										<input class="form-control" type="text" value="John Doe">
									</div>
									<div class="form-group">
										<label>Termination Type <span class="text-danger">*</span></label>
										<div class="add-group-btn">
											<select class="select">
												<option>Misconduct</option>
												<option>Others</option>
											</select>
											<a class="btn btn-primary" href="javascript:void(0);"><i class="fa fa-plus"></i> Add</a>
										</div>
									</div>
									<div class="form-group">
										<label>Termination Date <span class="text-danger">*</span></label>
										<div class="cal-icon">
											<input type="text" class="form-control datetimepicker" value="28/02/2019">
										</div>
									</div>
									<div class="form-group">
										<label>Reason <span class="text-danger">*</span></label>
										<textarea class="form-control" rows="4"></textarea>
									</div>
									<div class="form-group">
										<label>Notice Date <span class="text-danger">*</span></label>
										<div class="cal-icon">
											<input type="text" class="form-control datetimepicker" value="28/02/2019">
										</div>
									</div>
									<div class="submit-section">
										<button class="btn btn-primary submit-btn">Submit</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
				<!-- /Edit Termination Modal -->
				

			
            </div>
			<!-- /Page Wrapper -->

			{% endblock body %}