accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'


urlpatterns = [
    path('dashboard' , views.dashboard , name='dashboard'),
    path('profile/' , views.profile , name='profile'),
    path('projects' , views.project_list , name='projects'),
    path('projects/<int:id>' , views.project_detail , name='project_detail'),

    path('employees/' , views.employee_management , name='employee_list'),
    path('employees/export/excel' , views.employee_export_excel , name='employee_export_excel'),
    path('employee/<int:id>' , views.employee_detail,name='employee_detail'),
    # path('employees/attendance' , views.employees_attendance , name='employees_attendance'),
    # path('employees/attendance/<int:id>' , views.employee_attendance , name='employee_attendance'),
    
]

hr/urls.py
from django.urls import path
from . import views

app_name = 'hr'


urlpatterns = [


    path('employee/add' , views.employee_create , name='employee_create'),
    path('employee/<int:id>/edit' , views.employee_edit , name='employee_edit'),
    path('employee/<int:id>/delete' , views.employee_delete , name='employee_delete'),
    path('employees/attendance' , views.employees_attendance , name='employees_attendance'),
    path('employees/attendance/<int:id>' , views.employee_attendance , name='employee_attendance'),
    path('employee/reports' , views.employee_info_report , name='employee_info_report'),


    path('departments/' , views.deparment_management , name='department_list'),
    path('departments/add' , views.department_create , name='department_create'),
    path('departments/add' , views.department_create , name='department_create'),
    path('departments/<int:id>/edit' , views.department_edit , name='department_edit'),
    path('departments/<int:id>/delete' , views.department_delete , name='department_delete'),


    path('jobs/' , views.job_management , name='job_list'),
    path('jobs/add' , views.job_create , name='job_create'),
    path('jobs/<int:id>/edit' , views.job_edit , name='job_edit'),
    path('jobs/<int:id>/delete' , views.job_delete , name='job_delete'),


    path('salary/' , views.employee_salary_management , name='employee_salary_management'),


    ## training
    path('training/' , views.training_management , name='training_list'),
    path('training/add' , views.training_create , name='training_create'),
    path('training/<int:id>/edit' , views.training_edit , name='training_edit'),
    path('training/<int:id>/delete' , views.training_delete , name='training_delete'),
    path('training/<int:id>/status_change' , views.training_staus_update , name='training_staus_update'),
    
    ## training type
    path('training-type/' , views.training_type_management , name='training_type_list'),
    path('training-type/create' , views.training_type_create , name='training_type_create'),
    path('training-type/<int:id>/edit' , views.training_type_edit , name='training_type_edit'),
    path('training-type/<int:id>/delete' , views.training_type_delete , name='training_type_delete'),
    path('training-type/<int:id>/status_change' , views.training_type_staus_update , name='training_type_staus_update'),
    

    ## promotions
    path('promotions/' , views.promotion_management , name='promotion_list'),
    path('promotions/add' , views.promotion_create, name='promotion_create'),
    path('promotions/<int:id>/edit' , views.promotion_edit , name='promotion_edit'),
    path('promotions/<int:id>/delete' , views.promotion_delete , name='promotion_delete'),


    ## payroll
    path('payroll/adition' , views.payroll_addition , name='payroll_addition'),
    path('payroll/adition/create' , views.payroll_addition_create , name='payroll_addition_create'),
    path('payroll/adition/<int:id>/edit' , views.payroll_addition_edit , name='payroll_addition_edit'),
    path('payroll/adition/<int:id>/delete' , views.payroll_addition_delte , name='payroll_addition_delte'),


    path('payroll/overtime' , views.payroll_overtime , name='payroll_overtime'),
    path('payroll/overtime/create' , views.payroll_overtime_create , name='payroll_overtime_create'),
    path('payroll/overtime/<int:id>/edit' , views.payroll_overtime_edit , name='payroll_overtime_edit'),
    path('payroll/overtime/<int:id>/delete' , views.payroll_overtime_delete , name='payroll_overtime_delete'),

    path('payroll/payslip' , views.payslip_view , name='payroll_payslip'),

    ## promotions
    path('assets/' , views.asset_management , name='asset_list'),
    path('assets/add' , views.asset_create , name='asset_create'),
    path('assets/<int:id>/edit' , views.asset_edit , name='asset_edit'),
    path('assets/<int:id>/delete' , views.asset_delete , name='asset_delete'),




    path('termination/' , views.employee_termination , name='employee_termination'),
    path('termination/add' , views.employee_termination , name='employee_termination'),
    path('termination/<int:id>/delete' , views.employee_termination_delete , name='employee_termination_delete'),
    
    path('holidays/' , views.employee_holidays , name='employee_holidays'),
    path('holidays/add' , views.holiday_create , name='holiday_create'),
    path('holidays/<int:id>/delete' , views.holiday_delete , name='holiday_delete'),


    path('announcements' , views.all_anouncements , name='all_anouncements'),


    path('settings/company' , views.company_settings , name='company_settings')

]

managers/urls.py
from django.urls import path
from . import views
# from employee import views as em_views 

app_name = 'managers'


urlpatterns = [


    path('projects/add' , views.project_create , name='project_create'),
    path('projects/<int:id>/edit' , views.project_edit , name='project_edit'),
    path('projects/<int:id>/delete' , views.project_delete , name='project_delete'),
    path('projects/reports' , views.project_report , name='project_report'),



    path('clients/' , views.client_list , name='client_list'),
    path('clients/add' , views.client_create , name='client_create'),
    path('clients/<int:id>/edit' , views.client_edit , name='client_edit'),
    path('clients/<int:id>/delete' , views.client_delete , name='client_delete'),

]

project/urls.py
from django.urls import path , include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from settings.views import handel500

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('' , include('website.urls',namespace='website')),
    path('' , include('accounts.urls',namespace='accounts')),
    path('' , include('hr.urls',namespace='hr')),
    path('' , include('employee.urls',namespace='employee')),
    path('' , include('managers.urls',namespace='manager')),
    path('settings/' , include('settings.urls',namespace='setings')),
    path('500' , handel500, name='500_error'),

]



handler404= "settings.views.handel404"
handler500= "settings.views.handel500"


if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

managers/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from settings import models as st_model
from django.conf import settings

# Create your models here.


class Client(models.Model):
   company  = models.ForeignKey(st_model.Company, related_name='company_client', on_delete=models.CASCADE)
   name =  models.CharField(_("name"), max_length=100)
   mobile_number = models.CharField(max_length=18 , verbose_name=_('Mobile Number'), blank=True, null=True)
   email = models.EmailField(_("email"), max_length=254 , blank=True, null=True)
   address = models.CharField(max_length=200 , verbose_name=_('Address'), blank=True, null=True)

   def __str__(self):
     return self.name




class Project(models.Model):
    company  = models.ForeignKey(st_model.Company, related_name='company_project', on_delete=models.CASCADE)
    manager = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Manager'), related_name='project_manager', on_delete=models.CASCADE)
    name = models.CharField(_("name"), max_length=50)
    description = models.TextField(_("Description"))
    start_date = models.DateField(_("Start Date"), default=timezone.now)
    end_date = models.DateField(_("End Date"), default=timezone.now)
    piriority = models.ForeignKey(st_model.ProjectPeriority, verbose_name=_('Perioirty'), related_name='project_pirority', on_delete=models.CASCADE)
    leader = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Leader') ,related_name='leader_user', on_delete=models.CASCADE)
    team = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name=_("Team"),blank=True, null=True)
    attachment = models.FileField(_("Attachment"), upload_to='projects/')
    client = models.ForeignKey(Client, verbose_name=_('Client'), related_name='project_client', on_delete=models.CASCADE)
    status = models.ForeignKey(st_model.ProjectStatus, verbose_name=_('Status'), related_name='project_status', on_delete=models.CASCADE)

    def __str__(self):
        return self.name




class ProjectTask(models.Model):
    project = models.ForeignKey(Project, verbose_name=_('Project'), related_name='project_task', on_delete=models.CASCADE)
    tile = models.CharField(max_length=200, verbose_name=_('Title'))
    description = models.TextField(_("Description"))
    due_date = models.DateField(_("Due Date"), default=timezone.now)
    employee = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Employee'),related_name='task_employee', on_delete=models.CASCADE)
    status = models.ForeignKey(st_model.TaskStatus, verbose_name=_('Status'), related_name='task_status', on_delete=models.CASCADE)
    


# class Team(models.Model):
#     name = models.CharField(max_length=200)

managers/forms.py
from django import forms 
from . import models 
from django.forms.widgets import NumberInput




class ProjectForm(forms.ModelForm):
    start_date = forms.DateField(widget=NumberInput(attrs={'type': 'date'}))
    end_date = forms.DateField(widget=NumberInput(attrs={'type': 'date'}))
    class Meta:
        model = models.Project
        exclude = ['manager',]



class ClientForm(forms.ModelForm):
    class Meta:
        model = models.Client
        fields = '__all__'

managers/views.py
from django.shortcuts import render , redirect
from . import models 
from django.shortcuts  import get_object_or_404
from . import forms 
from django.contrib import messages
from accounts.models import User
from utils.ajax_form_save import save_form
from django.http import JsonResponse
from django.template.loader import render_to_string





def project_create(request):
    projects = models.Project.objects.all()
    if request.method == 'POST':
        form = forms.ProjectForm(request.POST ,request.FILES)

    else:
        form = forms.ProjectForm()
    return save_form(request,form,projects,'includes/project_list.html','includes/project_create.html')



def project_edit(request,id):
    project = get_object_or_404(models.Project , id=id)
    projects = models.Project.objects.all()
    if request.method == 'POST':
        form = forms.ProjectForm(request.POST ,request.FILES , instance=project)

    else:
        form = forms.ProjectForm(instance=project)

    return save_form(request,form,projects,'includes/project_list.html','includes/project_update.html')


def project_delete(request,id):
    project = get_object_or_404(models.Project , id=id)
    data = dict()
    if request.method == 'POST':
        project.delete()
        data['form_is_valid'] = True
        projects = models.Project.objects.all()
        data['model_list'] = render_to_string('includes/project_list.html',{'object_list':projects})
        
    else:
        data['form_is_valid'] = False
        context = {'project':project}
        data['html_form'] = render_to_string('includes/project_delete.html',context,request=request)
    return JsonResponse(data)



def project_report(request):
    projects = models.Project.objects.all()   # filter bu current manager
    return render(request,'managers/project-reports.html',{'projects':projects})






def client_list(request):
    clients = models.Client.objects.all()
    return render(request,'managers/clients.html',{'object_list':clients})



def client_create(request):
    clients = models.Client.objects.all()
    if request.method == 'POST':
        form = forms.ClientForm(request.POST)

    else:
        form = forms.ClientForm()
    return save_form(request,form,clients,'includes/client_list.html','includes/client_create.html')



def client_edit(request,id):
    client = get_object_or_404(models.Client , id=id)
    clients = models.Client.objects.all()
    if request.method == 'POST':
        form = forms.ClientForm(request.POST , instance=client)

    else:
        form = forms.ClientForm(instance=client)

    return save_form(request,form,clients,'includes/client_list.html','includes/client_update.html')


def client_delete(request,id):
    client = get_object_or_404(models.Client , id=id)
    data = dict()
    if request.method == 'POST':
        client.delete()
        data['form_is_valid'] = True
        clients = models.Client.objects.all()
        data['model_list'] = render_to_string('includes/client_list.html',{'object_list':clients})
        
    else:
        data['form_is_valid'] = False
        context = {'client':client}
        data['html_form'] = render_to_string('includes/client_delete.html',context,request=request)
    return JsonResponse(data)

managers/templates/includes/client_create.html
{% load i18n %}
{% load bootstrap4 %}
<div class="modal-header">
    <h5 class="modal-title">{% trans 'Create Client' %}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form method="POST" class="client_create_from" action="{% url 'manager:client_create' %}">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
        {% endbuttons %}
    </form>
</div>

managers/templates/includes/client_delete.html
{% load i18n %}
<div class="modal-body">
    <div class="form-header">
        <h3>{% trans 'Delete Job' %}</h3>
        <p>{% trans 'Are you sure want to delete?' %}</p>
    </div>
    <div class="modal-btn delete-action">
        <form method="POST" class="client_delete_from" action="{% url 'manager:client_delete' client.id %}">
            {% csrf_token %}
            <div class="row">
                <div class="col-6">
                    <button type="submit" class="btn btn-primary continue-btn">{% trans 'Delete' %}</button>
                </div>
                <div class="col-6">
                    <a href="javascript:void(0);" data-dismiss="modal" class="btn btn-primary cancel-btn">{% trans 'Cancel' %}</a>
                </div>
            </div>
        </form>
    </div>
</div>

managers/templates/includes/client_list.html
{% load i18n %}
{% for client in object_list  %}
<tr>
    <td>{{forloop.counter}}</td>
    <td>
        {{client.name}}
    </td>
    <td>{{client.mobile_number}}</td>
    <td>{{client.email}}</td>
    <td>{{client.address}}</td>
    <td class="text-right">
        <div class="dropdown dropdown-action">
            <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="material-icons">more_vert</i></a>
            <div class="dropdown-menu dropdown-menu-right">
                <button class="btn btn-info btn-sm-x  js-update" data-url="{% url 'manager:client_edit' client.id %}"><i class="fa fa-pencil m-r-5"></i>{% trans 'Edit' %}  </button>
                <button class="btn btn-danger btn-sm-x js-delete" data-url="{% url 'manager:client_delete' client.id %}"><i class="fa fa-trash-o m-r-5"></i> {% trans 'Delete' %} </button>
            </div>
        </div>
    </td>
</tr>
{% endfor %}

managers/templates/includes/client_update.html
{% load i18n %}
{% load bootstrap4 %}
<div class="modal-header">
    <h5 class="modal-title">{% trans 'Update Client' %}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form method="POST" class="client_save_from" action="{% url 'manager:client_edit' form.instance.pk %}">
        {% csrf_token %}
        {% bootstrap_form form%}
        {% buttons %}
        <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
        {% endbuttons %}
    </form>
</div>

managers/templates/includes/project_create.html
{% load i18n %}
{% load bootstrap4 %}
<div class="modal-header">
    <h5 class="modal-title">{% trans 'Create Project' %}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form method="POST" enctype="multipart/form-data" class="project_create_from" action="{% url 'manager:project_create' %}">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">{% bootstrap_field form.name %} </div>
            <div class="col-md-6">{% bootstrap_field form.client %}</div>
            <div class="col-md-6">{% bootstrap_field form.start_date %}</div>
            <div class="col-md-6">{% bootstrap_field form.end_date %}</div>
            <div class="col-md-6">{% bootstrap_field form.piriority %}</div>
            <div class="col-md-6">{% bootstrap_field form.leader %}</div>
            <div class="col-md-6">{% bootstrap_field form.team %}</div>
            <div class="col-md-6">{% bootstrap_field form.attachment %}</div>
            <div class="col-md-12">{% bootstrap_field form.description %}</div>
        </div>
        {% buttons %}
        <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
        {% endbuttons %}
    </form>
</div>

managers/templates/includes/project_delete.html
{% load i18n %}
<div class="modal-body">
    <div class="form-header">
        <h3>{% trans 'Delete Job' %}</h3>
        <p>{% trans 'Are you sure want to delete?' %}</p>
    </div>
    <div class="modal-btn delete-action">
        <form method="POST" class="project_delete_from" action="{% url 'manager:project_delete' project.id %}">
            {% csrf_token %}
            <div class="row">
                <div class="col-6">
                    <button type="submit" class="btn btn-primary continue-btn">{% trans 'Delete' %}</button>
                </div>
                <div class="col-6">
                    <a href="javascript:void(0);" data-dismiss="modal" class="btn btn-primary cancel-btn">{% trans 'Cancel' %}</a>
                </div>
            </div>
        </form>
    </div>
</div>

managers/templates/includes/project_list.html
{% load i18n %}
{% for project in object_list %}						
<div class="col-lg-4 col-sm-6 col-md-4 col-xl-3">
    <div class="card">
        <div class="card-body">
            {% if request.user.is_manager %}
                <div class="dropdown dropdown-action profile-action">
                    <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="material-icons">more_vert</i></a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <button class="btn btn-info btn-sm js-update" data-url="{% url 'manager:project_edit' project.id %}">{% trans 'Edit' %}  </button>
                        <button class="btn btn-danger btn-sm js-delete" data-url="{% url 'manager:project_delete' project.id %}">{% trans 'Delete' %}  </button>
                    </div>
                </div>
            {% endif %}
            <h4 class="project-title"><a href="{% url 'accounts:project_detail' project.id %}">{{project.name}}</a></h4>
            <p class="text-muted">{{project.description}}
            </p>
            <div class="pro-deadline m-b-15">
                <div class="sub-title">
                    {% trans 'Deadline' %}:
                </div>
                <div class="text-muted">
                    {{project.end_date}}
                </div>
            </div>
            <div class="project-members m-b-15">
                <div>{% trans 'Project Leader' %} :</div>
                <ul class="team-members">
                    <li>
                        <a href="#" data-toggle="tooltip" title="{{project.leader}}"><img alt="" src="{{project.leader.user_profile.image.url}}"></a>
                    </li>
                </ul>
            </div>
            <div class="project-members m-b-15">
                <div>{% trans 'Team' %} :</div>
                <ul class="team-members">
                    
                    {% for employee in project.team.all %}	
                        <li>
                            <a href="#" data-toggle="tooltip" title="{{employee}}">{% if employee.user_profile.image %}<img alt="" src="{{employee.user_profile.image.url}}"> {% endif %}</a>
                        </li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    </div>
</div>
{% endfor %}

managers/templates/includes/project_update.html
{% load i18n %}
{% load bootstrap4 %}
<div class="modal-header">
    <h5 class="modal-title">{% trans 'Create Project' %}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form method="POST" enctype="multipart/form-data" class="project_save_from" action="{% url 'manager:project_edit' form.instance.pk %}">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">{% bootstrap_field form.name %} </div>
            <div class="col-md-6">{% bootstrap_field form.client %}</div>
            <div class="col-md-6">{% bootstrap_field form.start_date %}</div>
            <div class="col-md-6">{% bootstrap_field form.end_date %}</div>
            <div class="col-md-6">{% bootstrap_field form.piriority %}</div>
            <div class="col-md-6">{% bootstrap_field form.leader %}</div>
            <div class="col-md-6">{% bootstrap_field form.team %}</div>
            <div class="col-md-6">{% bootstrap_field form.attachment %}</div>
            <div class="col-md-12">{% bootstrap_field form.description %}</div>
        </div>
        {% buttons %}
        <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
        {% endbuttons %}
    </form>
</div>