hr/urls.py
from django.urls import path
from . import views

app_name = 'hr'


urlpatterns = [


    path('employee/add' , views.employee_create , name='employee_create'),
    path('employee/<int:id>/edit' , views.employee_edit , name='employee_edit'),
    path('employee/<int:id>/delete' , views.employee_delete , name='employee_delete'),
    path('employees/attendance' , views.employees_attendance , name='employees_attendance'),
    path('employees/attendance/<int:id>' , views.employee_attendance , name='employee_attendance'),
    path('employee/reports' , views.employee_info_report , name='employee_info_report'),


    path('departments/' , views.deparment_management , name='department_list'),
    path('departments/add' , views.department_create , name='department_create'),
    path('departments/add' , views.department_create , name='department_create'),
    path('departments/<int:id>/edit' , views.department_edit , name='department_edit'),
    path('departments/<int:id>/delete' , views.department_delete , name='department_delete'),


    path('jobs/' , views.job_management , name='job_list'),
    path('jobs/add' , views.job_create , name='job_create'),
    path('jobs/<int:id>/edit' , views.job_edit , name='job_edit'),
    path('jobs/<int:id>/delete' , views.job_delete , name='job_delete'),


    path('salary/' , views.employee_salary_management , name='employee_salary_management'),


    ## training
    path('training/' , views.training_management , name='training_list'),
    path('training/add' , views.training_create , name='training_create'),
    path('training/<int:id>/edit' , views.training_edit , name='training_edit'),
    path('training/<int:id>/delete' , views.training_delete , name='training_delete'),
    path('training/<int:id>/status_change' , views.training_staus_update , name='training_staus_update'),
    
    ## training type
    path('training-type/' , views.training_type_management , name='training_type_list'),
    path('training-type/create' , views.training_type_create , name='training_type_create'),
    path('training-type/<int:id>/edit' , views.training_type_edit , name='training_type_edit'),
    path('training-type/<int:id>/delete' , views.training_type_delete , name='training_type_delete'),
    path('training-type/<int:id>/status_change' , views.training_type_staus_update , name='training_type_staus_update'),
    

    ## promotions
    path('promotions/' , views.promotion_management , name='promotion_list'),
    path('promotions/add' , views.promotion_create, name='promotion_create'),
    path('promotions/<int:id>/edit' , views.promotion_edit , name='promotion_edit'),
    path('promotions/<int:id>/delete' , views.promotion_delete , name='promotion_delete'),


    ## payroll
    path('payroll/adition' , views.payroll_addition , name='payroll_addition'),
    path('payroll/adition/create' , views.payroll_addition_create , name='payroll_addition_create'),
    path('payroll/adition/<int:id>/edit' , views.payroll_addition_edit , name='payroll_addition_edit'),
    path('payroll/adition/<int:id>/delete' , views.payroll_addition_delte , name='payroll_addition_delte'),


    path('payroll/overtime' , views.payroll_overtime , name='payroll_overtime'),
    path('payroll/overtime/create' , views.payroll_overtime_create , name='payroll_overtime_create'),
    path('payroll/overtime/<int:id>/edit' , views.payroll_overtime_edit , name='payroll_overtime_edit'),
    path('payroll/overtime/<int:id>/delete' , views.payroll_overtime_delete , name='payroll_overtime_delete'),

    path('payroll/payslip' , views.payslip_view , name='payroll_payslip'),

    ## promotions
    path('assets/' , views.asset_management , name='asset_list'),
    path('assets/add' , views.asset_create , name='asset_create'),
    path('assets/<int:id>/edit' , views.asset_edit , name='asset_edit'),
    path('assets/<int:id>/delete' , views.asset_delete , name='asset_delete'),




    path('termination/' , views.employee_termination , name='employee_termination'),
    path('termination/add' , views.employee_termination , name='employee_termination'),
    path('termination/<int:id>/delete' , views.employee_termination_delete , name='employee_termination_delete'),
    
    path('holidays/' , views.employee_holidays , name='employee_holidays'),
    path('holidays/add' , views.holiday_create , name='holiday_create'),
    path('holidays/<int:id>/delete' , views.holiday_delete , name='holiday_delete'),


    path('announcements' , views.all_anouncements , name='all_anouncements'),


    path('settings/company' , views.company_settings , name='company_settings')

]

project/urls.py
from django.urls import path , include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from settings.views import handel500

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('' , include('website.urls',namespace='website')),
    path('' , include('accounts.urls',namespace='accounts')),
    path('' , include('hr.urls',namespace='hr')),
    path('' , include('employee.urls',namespace='employee')),
    path('' , include('managers.urls',namespace='manager')),
    path('settings/' , include('settings.urls',namespace='setings')),
    path('500' , handel500, name='500_error'),

]



handler404= "settings.views.handel404"
handler500= "settings.views.handel500"


if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings/urls.py
from django.urls import path
from . import views

app_name = 'settings'


urlpatterns = [
    path('asset-condition' , views.AssetConditionListCreateView.as_view(),name='asset-condition-list-create'),
    path('asset-condition/<int:id>/delete' , views.asset_Condition_delete,name='asset-condition-delete'),

    path('asset-status' , views.AssetStatusListCreateView.as_view(),name='asset-status-List-Create'),
    path('asset-status/<int:id>/delete' , views.asset_status_delete,name='asset-status-delete'),

    path('attendance-types' , views.AttendanceTypesListCreateView.as_view(),name='attendance-types-List-Create'),
    path('attendance-types/<int:id>/delete' , views.attendance_types_delete,name='attendance-types-delete'),

    path('bank-names' , views.BankNamesListCreateView.as_view(),name='bank-names-List-Create'),
    path('bank-names/<int:id>/delete' , views.bank_names_delete,name='bank-names-delete'),

    path('branch' , views.BranchesListCreateView.as_view(),name='branch-List-Create'),
    path('branch/<int:id>/delete' , views.branch_delete,name='branch-delete'),

    path('city' , views.CityListCreateView.as_view(),name='city-List-Create'),
    path('city/<int:id>/delete' , views.city_delete,name='city-delete'),

    path('discount-types' , views.DiscountTypesListCreateView.as_view(),name='discount-types-List-Create'),
    path('discount-types/<int:id>/delete' , views.discount_types_delete,name='discount-types-delete'),

    path('employee-status' , views.EmployeeStatusListCreateView.as_view(),name='employee-status-List-Create'),
    path('employee-status/<int:id>/delete' , views.employee_status_delete,name='employee-status-delete'),

    path('follower-types' , views.FollowerTypesListCreateView.as_view(),name='follower-types-List-Create'),
    path('follower-types/<int:id>/delete' , views.follower_type_delete,name='follower-types-delete'),

    path('insurance-class' , views.InsuranceClassListCreateView.as_view(),name='insurance-class-List-Create'),
    path('insurance-class/<int:id>/delete' , views.insurance_class_delete,name='insurance-class-delete'),

    path('insurance-company' , views.InsuranceCompanyListCreateView.as_view(),name='insurance-company-List-Create'),
    path('insurance-company/<int:id>/delete' , views.insurance_company_delete,name='insurance-company-delete'),

    path('job-grade' , views.JobGradeListCreateView.as_view(),name='job-grade-List-Create'),
    path('job-grade/<int:id>/delete' , views.job_grade_delete,name='job-grade-delete'),

    path('project-periority' , views.ProjectPeriorityListCreateView.as_view(),name='project-periority-List-Create'),
    path('project-periority/<int:id>/delete' , views.project_periority_delete,name='project-periority-delete'),

    path('project-status' , views.ProjectStatusListCreateView.as_view(),name='project-status-List-Create'),
    path('project-status/<int:id>/delete' , views.project_status_delete,name='project-status-delete'),

    path('qualifications' , views.QualificationListCreateView.as_view(),name='qualifications-List-Create'),
    path('qualifications/<int:id>/delete' , views.qualifications_delete,name='qualifications-delete'),

    path('reason-to-terminate' , views.ReasonToTerminateListCreateView.as_view(),name='reason-to-terminate-List-Create'),
    path('reason-to-terminate/<int:id>/delete' , views.reason_to_terminate_delete,name='reason-to-terminate-delete'),


    path('replacement-period' , views.ReplacementPeriodListCreateView.as_view(),name='replacement-period-List-Create'),
    path('replacement-period/<int:id>/delete' , views.replacement_period_delete,name='replacement-period-delete'),

    path('replacement-type' , views.ReplacementTypeListCreateView.as_view(),name='replacement-type-List-Create'),
    path('replacement-type/<int:id>/delete' , views.replacement_type_delete,name='replacement-type-delete'),

    path('salary-pay-types' , views.SalaryPayTypesListCreateView.as_view(),name='salary-pay-types-List-Create'),
    path('salary-pay-types/<int:id>/delete' , views.salary_pay_types_delete,name='salary-pay-types-delete'),

    path('salary-type' , views.SalaryTypeListCreateView.as_view(),name='salary-type-List-Create'),
    path('salary-type/<int:id>/delete' , views.salary_type_delete,name='salary-type-delete'),

    path('ticket-type' , views.TcketTypeListCreateView.as_view(),name='ticket-type-List-Create'),
    path('ticket-type/<int:id>/delete' , views.ticket_type_delete,name='ticket-type-delete'),

]

templates/settings_base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
        <meta name="description" content="Smarthr - Bootstrap Admin Template">
		<meta name="keywords" content="admin, estimates, bootstrap, business, corporate, creative, management, minimal, modern, accounts, invoice, html5, responsive, CRM, Projects">
        <meta name="author" content="Dreamguys - Bootstrap Admin Template">
        <meta name="robots" content="noindex, nofollow">
        <title>{{info.website_name}}</title>
		
		<!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="{{info.fav_icon.url}}">
		
		{% get_current_language as LANGUAGE_CODE %}
		{{LANGUAGE_CODE}}

		{% if LANGUAGE_CODE == 'en' %}
		<!-- Bootstrap CSS -->
        	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
			{% endif %}

		{% if LANGUAGE_CODE == 'ar' %}
			<link rel="stylesheet" href="{% static 'plugins/bootstrap-rtl/css/bootstrap.min.css' %}">
			<link rel="preconnect" href="https://fonts.googleapis.com">
			<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
			<link href="https://fonts.googleapis.com/css2?family=Almarai:wght@300;400;700;800&display=swap" rel="stylesheet"> 
		{% endif %}
		
		<!-- Fontawesome CSS -->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
		
		<!-- Lineawesome CSS -->
        <link rel="stylesheet" href="{% static 'css/line-awesome.min.css' %}">
		
		<!-- Main CSS -->
		{% if LANGUAGE_CODE == 'en' %}
			<link rel="stylesheet" href="{% static 'css/style.css' %}">
		{% endif %}

		{% if LANGUAGE_CODE == 'ar' %}
			<link rel="stylesheet" href="{% static 'css/style-rtl.css' %}">
		{% endif %}
		
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="{% static 'js/html5shiv.min.js"></script>
			<script src="{% static 'js/respond.min.js"></script>
		<![endif]-->
    </head>
    <body>
		<!-- Main Wrapper -->
        <div class="main-wrapper">
		
			<!-- Header -->
            <div class="header">
			
				<!-- Logo -->
                <div class="header-left">
                    <a href="/dashboard" class="logo">
						<img src="{{info.logo.url}}" width="40" height="40" alt="">
					</a>
                </div>
				<!-- /Logo -->
				
				<a id="toggle_btn" href="javascript:void(0);">
					<span class="bar-icon">
						<span></span>
						<span></span>
						<span></span>
					</span>
				</a>
				
				<!-- Header Title -->
                <div class="page-title-box">
					<h3>{{info.website_name}}</h3>
                </div>
				<!-- /Header Title -->
				
				<a id="mobile_btn" class="mobile_btn" href="#sidebar"><i class="fa fa-bars"></i></a>
				
				<!-- Header Menu -->
				<ul class="nav user-menu">
				
					<!-- Flag -->
					<li class="nav-item dropdown has-arrow flag-nav">
						<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button">
							<img src="{% static 'img/flags/us.png' %}" alt="" height="20"> <span>English</span>
						</a>
						<div class="dropdown-menu dropdown-menu-right">
							<a href="javascript:void(0);" class="dropdown-item">
								<img src="{% static 'img/flags/us.png' %}" alt="" height="16"> {% trans 'English' %}
							</a>
							<a href="javascript:void(0);" class="dropdown-item">
								<img src="{% static 'img/flags/sa.png' %}" alt="" height="16"> {% trans 'Arabic' %}
							</a>
						</div>
					</li>
					<!-- /Flag -->
				
					<!-- Notifications -->
					<li class="nav-item dropdown">
						<a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
							<i class="fa fa-bell-o"></i> <span class="badge badge-pill">3</span>
						</a>
						<div class="dropdown-menu notifications">
							<div class="topnav-dropdown-header">
								<span class="notification-title">Notifications</span>
								<a href="javascript:void(0)" class="clear-noti"> Clear All </a>
							</div>
							<div class="noti-content">
								<ul class="notification-list">
									
									{% for announcement in announcements %}
									<li class="notification-message">
										<a href="activities.html">
											<div class="media">
												<div class="media-body">
													<p class="noti-details"><span class="noti-title">{{announcement.title}} </p>
													<p><span class="noti-title">{{announcement.message}}</span></p>
													<p class="noti-time"><span class="notification-time">{{announcement.created_at|timesince}} ago</span></p>
												</div>
											</div>
										</a>
									</li>
									{% endfor %}

								</ul>
							</div>
							<div class="topnav-dropdown-footer">
								<a href="activities.html">View all Notifications</a>
							</div>
						</div>
					</li>
					<!-- /Notifications -->
					

					<li class="nav-item dropdown has-arrow main-drop">
						<a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
							<span class="user-img"><img src="{{user.image.url}}" alt="">
							<span class="status online"></span></span>
							<span>{{user.user.username}}</span>
						</a>
						<div class="dropdown-menu">
							<a class="dropdown-item" href="">My Profile</a>
							<a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
							<a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
						</div>
					</li>
				</ul>
				<!-- /Header Menu -->
				
				<!-- Mobile Menu -->
				<div class="dropdown mobile-user-menu">
					<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
					<div class="dropdown-menu dropdown-menu-right">
						<a class="dropdown-item" href="profile.html">My Profile</a>
						<a class="dropdown-item" href="settings.html">Settings</a>
						<a class="dropdown-item" href="login.html">Logout</a>
					</div>
				</div>
				<!-- /Mobile Menu -->
				
            </div>
			<!-- /Header -->
			
			<!-- Sidebar -->
            <div class="sidebar" id="sidebar">
                <div class="sidebar-inner slimscroll">
					<div class="sidebar-menu">
						<ul>
							<li> 
								<a href="/dashboard"><i class="la la-home"></i> <span>{% trans 'Back to Home' %}</span></a>
							</li>
							<li class="menu-title">{% trans 'Settings' %}</li>
							<li class="active"> 
								<a href=""><i class="la la-building"></i> <span>{% trans 'Company Settings' %}</span></a>
							</li>
							<li> 
								<a href=""><i class="la la-clock-o"></i> <span>{% trans 'Localization' %}</span></a>
							</li>
							<li > 
								<a href=""><i class="la la-photo"></i> <span>{% trans 'Theme Settings' %}</span></a>
							</li>
							<li {% if branch_list %} class="active" {% endif %}> 
								<a href="{% url 'settings:branch-List-Create' %}"><i class="la la-key"></i> <span>{% trans 'Branches' %}</span></a>
							</li>
							<li> 
								<a href=""><i class="la la-at"></i> <span>{% trans 'Email Settings' %}</span></a>
							</li>
							<li {% if city_list %} class="active" {% endif %}> 
                                <a href="{% url 'settings:city-List-Create' %}"><i class="la la-chart-bar"></i> <span>{% trans 'City Settings' %}</span></a>
                            </li>
                            <li{% if assetcondition_list %} class="active" {% endif %}> 
                                <a href="{% url 'settings:asset-condition-list-create' %}"><i class="la la-thumbs-up"></i> <span>{% trans 'Asset Condition' %}</span></a>
                            </li>
							<li> 
								<a href="{% url 'settings:asset-status-List-Create' %}"><i class="la la-pencil-square"></i> <span>{% trans 'Asset Status' %} </span></a>
							</li>
							<li> 
								<a href="{% url 'settings:attendance-types-List-Create' %}"><i class="la la-money"></i> <span>{% trans 'Attendance Types' %}</span></a>
							</li>
							<li> 
								<a href="{% url 'settings:bank-names-List-Create' %}"><i class="la la-globe"></i> <span>{% trans 'Bank Names' %}</span></a>
							</li>
							<li> 
								<a href=""><i class="la la-lock"></i> <span>{% trans 'Default Password' %}</span></a>
							</li>
							<li> 
								<a href="{% url 'settings:discount-types-List-Create' %}"><i class="la la-comment"></i> <span>{% trans 'Discount Types' %} </span></a>
							</li>
							<li> 
								<a href="{% url 'settings:employee-status-List-Create' %}"><i class="la la-rocket"></i> <span>{% trans 'Employee Status' %} </span></a>
							</li>
							<li> 
								<a href="{% url 'settings:follower-types-List-Create' %}"><i class="la la-cogs"></i> <span>{% trans 'Follower Types' %} </span></a>
							</li>
							<li> 
								<a href="{% url 'settings:insurance-class-List-Create' %}"><i class="la la-comment"></i> <span>{% trans 'Insurance Class' %}  </span></a>
							</li>
							<li> 
								<a href="{% url 'settings:insurance-company-List-Create' %}"><i class="la la-rocket"></i> <span>{% trans 'Insurance Company ' %} </span></a>
							</li>

							<li> 
								<a href="{% url 'settings:job-grade-List-Create' %}"><i class="la la-cogs"></i> <span>{% trans 'Job Grades ' %}</span></a>
							</li>
							<li> 
								<a href="{% url 'settings:project-periority-List-Create' %}"><i class="la la-rocket"></i> <span>{% trans 'Project Periority' %}  </span></a>
							</li>
							<li> 
								<a href="{% url 'settings:project-status-List-Create' %}"><i class="la la-cogs"></i> <span>{% trans 'Project Status ' %} </span></a>
							</li>
							<li {% if qualification_list %} class="active" {% endif %}> 
								<a href="{% url 'settings:qualifications-List-Create' %}"><i class="la la-comment"></i> <span>{% trans 'Qualifications' %}   </span></a>
							</li>
							<li> 
								<a href="{% url 'settings:reason-to-terminate-List-Create' %}"><i class="la la-rocket"></i> <span>{% trans 'Reasons To Terminate ' %}</span></a>
							</li>
							<li> 
								<a href="{% url 'settings:replacement-period-List-Create' %}"><i class="la la-cogs"></i> <span>{% trans 'Replacement Periods' %}  </span></a>
							</li>
							<li> 
								<a href="{% url 'settings:replacement-type-List-Create' %}"><i class="la la-comment"></i> <span>{% trans 'Replacement Types' %} </span></a>
							</li>
							<li> 
								<a href="{% url 'settings:salary-pay-types-List-Create' %}"><i class="la la-rocket"></i> <span>{% trans 'Salary Pay Types ' %} </span></a>
							</li>
							<li> 
								<a href="{% url 'settings:salary-type-List-Create' %}"><i class="la la-cogs"></i> <span>{% trans 'Salary Types' %}   </span></a>
							</li>
							<li> 
								<a href="{% url 'settings:ticket-type-List-Create' %}"><i class="la la-comment"></i> <span>{% trans 'Ticket Types ' %}  </span></a>
							</li>

						</ul>
					</div>
                </div>
            </div>
			<!-- /Sidebar -->
			
			<!-- Page Wrapper -->
            {% block content %}
              
            {% endblock content %}
			<!-- /Page Wrapper -->
			{% for message in messages %}
				<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
					{{message}}
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
		{% endfor %}

        </div>
		<!-- /Main Wrapper -->
		<style>
			.alert{
				position: fixed;
				top: 62px;
				right: 37%;
			}
		</style>

		<!-- jQuery -->
        <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>

		<!-- Bootstrap Core JS -->
        <script src="{% static 'js/popper.min.js' %}"></script>

		{% if LANGUAGE_CODE == 'en' %}
			<script src="{% static 'js/bootstrap.min.js' %}"></script>
		{% endif %}
        
		
		{% if LANGUAGE_CODE == 'ar' %}
			<script src="{% static 'plugins/bootstrap-rtl/js/bootstrap.min.js' %}"></script>
		{% endif %}

		<!-- Slimscroll JS -->
		<script src="{% static 'js/jquery.slimscroll.min.js' %}"></script>

		<!-- Custom JS -->
		<script src="{% static 'js/app.js' %}"></script>

		<script>
			window.setTimeout(function() {
				$(".alert").fadeTo(500, 0).slideUp(500, function(){
					$(this).remove(); 
				});
			}, 4000);
		</script>
		
    </body>
</html>